apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: holmes-ui
  namespace: obs-holmes-ui
  annotations:
    haproxy.router.openshift.io/timeout: 600s
spec:
  host: holmes-ui.observestack.fis-cloud.xplat.online
  to:
    kind: Service
    name: web
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
