apiVersion: v1
kind: Secret
metadata:
  name: holmes-ui-api
type: Opaque
stringData:
  APP_SECRET: 08f3ba483de0a74d1311cfe9ab1b3dee01380a666a926126c1d1f3c29b3f0485762ee61111bea454acc83b4af0f6e1a3
  ADMIN_PASSWORD: dGQeIe59N1lVrhzJ51hCJcEi
  HOLMES_API_KEY: ""
  ALERT_INGEST_TOKEN: ""
  CHANGE_INGEST_TOKEN: ""
  BOT_WEBHOOK_TOKEN: ""
  OIDC_CLIENT_SECRET: ""
